name: Backup existing tag
description: Creates a backup of the current latest tag before updating

runs:
  using: composite
  steps:
    - name: Backup existing tag
      shell: bash
      run: |
        echo "Checking if tag exists..."
        EXISTS=$(az acr repository show-tags \
          --name ${{ env.ACR_NAME }} \
          --repository ${{ env.REPO }} \
          --query "[?(@=='latest')]" -o tsv)

        if [ -n "$EXISTS" ]; then
          BACKUP_TAG="build-${{ github.run_id }}"
          
          # Check if backup tag already exists
          BACKUP_EXISTS=$(az acr repository show-tags \
            --name ${{ env.ACR_NAME }} \
            --repository ${{ env.REPO }} \
            --query "[?(@=='$BACKUP_TAG')]" -o tsv)
          
          if [ -z "$BACKUP_EXISTS" ]; then
            echo "Tag exists. Creating backup tag $BACKUP_TAG..."
            az acr import \
              --name ${{ env.ACR_NAME }} \
              --source ${{ env.ACR_LOGIN_SERVER }}/${{ env.REPO }}:latest \
              --image ${{ env.REPO }}:$BACKUP_TAG
          else
            echo "Backup tag $BACKUP_TAG already exists. Skipping backup."
          fi
        else
          echo "Tag not found. Skipping backup."
        fi
