name: Update Azure Container App
description: Updates the Azure Container App with the new Docker image

runs:
  using: composite
  steps:
    - name: Update Azure Container App
      shell: bash
      run: |
        echo "Updating ACA..."

        az containerapp update \
          --name ${{ env.ACA_NAME }} \
          --resource-group ${{ env.ACA_RG }} \
          --image ${{ env.ACR_LOGIN_SERVER }}/${{ env.REPO }}:latest

        echo "Container App updated. Current revisions:"
        az containerapp revision list \
          --name ${{ env.ACA_NAME }} \
          --resource-group ${{ env.ACA_RG }} \
          --output table
