name: "Backup Docker Image Tags"
description: "Backup current Docker image tags from ACR"

inputs:
  acr-login-server:
    description: "ACR login server"
    required: true
  repo:
    description: "Repository name in ACR"
    required: true
  backup-location:
    description: "Backup file location"
    required: false
    default: "./acr-backup"

outputs:
  backup-file:
    description: "Path to backup file"
    value: ${{ steps.backup.outputs.backup-file }}

runs:
  using: "composite"
  steps:
    - name: Create Backup Directory
      shell: bash
      run: |
        mkdir -p ${{ inputs.backup-location }}
        echo "Backup directory created"

    - name: Backup Image Tags
      id: backup
      shell: bash
      run: |
        BACKUP_FILE="${{ inputs.backup-location }}/backup-${{ inputs.repo }}-$(date +%Y%m%d-%H%M%S).json"

        echo "Fetching all tags for ${{ inputs.repo }}..."
        az acr repository show-tags \
          --name $(echo ${{ inputs.acr-login-server }} | cut -d. -f1) \
          --repository ${{ inputs.repo }} \
          --output json > $BACKUP_FILE

        echo "backup-file=$BACKUP_FILE" >> $GITHUB_OUTPUT
        echo "✅ Backup completed: $BACKUP_FILE"
        echo "Tags backed up:"
        cat $BACKUP_FILE
