name: Backup ACR Image Tags
description: Backup all tags of an ACR repository to a JSON file

inputs:
  acr-name:
    description: Azure Container Registry name (NOT login server)
    required: true
  repo:
    description: Repository name inside ACR
    required: true
  backup-location:
    description: Directory to store backup files
    required: true

runs:
  using: composite
  steps:
    - name: Create backup directory
      shell: bash
      run: |
        mkdir -p "${{ inputs.backup-location }}"
        echo "Backup directory created"

    - name: Backup ACR tags
      shell: bash
      run: |
        set -e

        BACKUP_FILE="${{ inputs.backup-location }}/backup-${{ inputs.repo }}-$(date +%Y%m%d-%H%M%S).json"

        echo "Fetching tags for repository '${{ inputs.repo }}' from ACR '${{ inputs.acr-name }}'..."

        az acr repository show-tags \
          --name "${{ inputs.acr-name }}" \
          --repository "${{ inputs.repo }}" \
          --output json > "$BACKUP_FILE"

        echo "backup-file=$BACKUP_FILE" >> "$GITHUB_OUTPUT"

        echo "✅ Backup completed: $BACKUP_FILE"
        echo "Tags backed up:"
        cat "$BACKUP_FILE"
