name: Cleanup old build tags
description: Removes old backup build tags, keeping only the 10 most recent

runs:
  using: composite
  steps:
    - name: Cleanup old build tags
      shell: bash
      run: |
        TAGS=$(az acr repository show-tags \
          --name ${{ env.ACR_NAME }} \
          --repository ${{ env.REPO }} \
          --query "[?starts_with(@, 'build-')]" \
          -o tsv | sort -r)

        COUNT=0
        for TAG in $TAGS; do
          COUNT=$((COUNT+1))
          if [ $COUNT -le 10 ]; then
            echo "Keeping $TAG"
          else
            echo "Deleting $TAG"
            az acr repository delete \
              --name ${{ env.ACR_NAME }} \
              --image ${{ env.REPO }}:$TAG \
              --yes || echo "Tag $TAG already deleted or not found, skipping..."
          fi
        done
