name: "Push Docker Image to ACR"
description: "Push Docker image to Azure Container Registry"

inputs:
  acr-login-server:
    description: "ACR login server (e.g., myacr.azurecr.io)"
    required: true
  image-name:
    description: "Docker image name"
    required: true
  image-tag:
    description: "Docker image tag"
    required: false
    default: "latest"

outputs:
  acr-image-url:
    description: "Full ACR image URL"
    value: ${{ steps.push.outputs.acr-image-url }}

runs:
  using: "composite"
  steps:
    - name: Push Image to ACR
      id: push
      shell: bash
      run: |
        ACR_IMAGE_URL="${{ inputs.acr-login-server }}/${{ inputs.image-name }}:${{ inputs.image-tag }}"

        echo "Tagging image..."
        docker tag ${{ inputs.image-name }}:${{ inputs.image-tag }} $ACR_IMAGE_URL

        echo "Pushing to ACR: $ACR_IMAGE_URL"
        docker push $ACR_IMAGE_URL

        echo "acr-image-url=$ACR_IMAGE_URL" >> $GITHUB_OUTPUT
        echo "✅ Image pushed successfully to: $ACR_IMAGE_URL"
