name: Push Docker image
description: Pushes the built Docker image to Azure Container Registry

runs:
  using: composite
  steps:
    - name: Push Docker image
      shell: bash
      run: |
        echo "Pushing image to ACR..."
        docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.REPO }}:latest

        echo "Image pushed successfully"
