name: "Build Docker Image"
description: "Build Docker image from Dockerfile"

inputs:
  dockerfile-path:
    description: "Path to Dockerfile"
    required: true
    default: "Dockerfile"
  image-name:
    description: "Docker image name"
    required: true
  image-tag:
    description: "Docker image tag"
    required: false
    default: "latest"
  build-context:
    description: "Docker build context"
    required: false
    default: "."
  build-args:
    description: "Build arguments (JSON format)"
    required: false

outputs:
  image-full-name:
    description: "Full image name with tag"
    value: ${{ steps.build.outputs.image-full-name }}

runs:
  using: "composite"
  steps:
    - name: Build Docker Image
      id: build
      shell: bash
      run: |
        IMAGE_FULL_NAME="${{ inputs.image-name }}:${{ inputs.image-tag }}"
        echo "Building: $IMAGE_FULL_NAME"

        docker build \
          -f ${{ inputs.dockerfile-path }} \
          -t $IMAGE_FULL_NAME \
          ${{ inputs.build-context }}

        echo "image-full-name=$IMAGE_FULL_NAME" >> $GITHUB_OUTPUT
        echo "✅ Docker image built successfully: $IMAGE_FULL_NAME"
