name: "Cleanup Old Docker Images"
description: "Remove old Docker images from ACR based on retention policy"

inputs:
  acr-login-server:
    description: "ACR login server"
    required: true
  repo:
    description: "Repository name in ACR"
    required: true
  keep-count:
    description: "Number of images to keep"
    required: false
    default: "10"
  older-than-days:
    description: "Delete images older than X days"
    required: false
    default: "30"

runs:
  using: "composite"
  steps:
    - name: Cleanup Old Images
      shell: bash
      run: |
        ACR_NAME=$(echo ${{ inputs.acr-login-server }} | cut -d. -f1)
        REPO=${{ inputs.repo }}
        KEEP_COUNT=${{ inputs.keep-count }}
        OLDER_THAN_DAYS=${{ inputs.older-than-days }}

        echo "Fetching all tags for $REPO..."
        TAGS=$(az acr repository show-tags \
          --name $ACR_NAME \
          --repository $REPO \
          --orderby time_desc \
          --output tsv)

        echo "Current tags:"
        echo "$TAGS"

        TAG_COUNT=0
        DELETED_COUNT=0

        while IFS= read -r TAG; do
          TAG_COUNT=$((TAG_COUNT + 1))
          
          if [ $TAG_COUNT -gt $KEEP_COUNT ]; then
            echo "Deleting old image: $REPO:$TAG"
            az acr repository delete \
              --name $ACR_NAME \
              --image $REPO:$TAG \
              --yes
            DELETED_COUNT=$((DELETED_COUNT + 1))
          fi
        done <<< "$TAGS"

        echo "✅ Cleanup completed!"
        echo "Kept: $KEEP_COUNT images"
        echo "Deleted: $DELETED_COUNT images"
